### ISSUE TITLE
Popping ViewController while keyboard is displayed results in EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Jack-s** [freak4pc/SMTagField#8] opened 2013-11-08 04:57 UTC
I was trying to use the SMTagField in a UITableViewCell, one of the issues I encountered was that if I press the back button (using a navigation controller) resulted in a EXC_BAD_ACCESS error.

 I was able to reproduce this error in the included example project by using a navigation controller with a view controller before the "ViewController" with the SMTagField (this way there is a back button in the menu) and then entering the edit mode by tapping the field, pressing back (popping the view controller), redisplaying the view controller and tapping the field and then pressing back again. The second time pressing back throws the EXC_BAD_ACCESS error.

**Comment by freak4pc** [comment] 2013-11-10 10:54
Hey @Jack-s, 
Could you attach your example project so I can reproduce the crash on my end? 
I've used it in many projects with UINavigationController and never had an issue.

Shai.

**Comment by Jack-s** [comment] 2013-11-10 12:34
Sure (I was planning on coin so originally but i didn't see a way to attach issues directly).

[Here's a link](http://sdrv.ms/16SK32W) 

Thanks

**Comment by freak4pc** [comment] 2013-11-10 13:27
Hey @Jack-s , Thanks for the example.
Could you try adding this `dealloc` to `SMTagField.m` ? 

``` obj-c
-(void)dealloc{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"UITextFieldTextDidChangeNotification" object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"UITextFieldTextDidEndEditingNotification" object:nil];
}
```

**Comment by Jack-s** [comment] 2013-11-10 14:07
That did the trick.

Thanks

**Comment by freak4pc** [comment] 2013-11-10 14:14
I'm gonna add that to the repo. Thanks for the bug update.

**Comment by freak4pc** [comment] 2013-11-10 14:27
Fixed in the referenced new commit. Cheers.

**Closed as completed by freak4pc** 2013-11-10 14:27 UTC

**Comment by Jack-s** [comment] 2013-11-10 15:50
Thanks.

 A quick question if you don't mind. I see that in the layout tags method you are adding a target action for `tagTapped`

 [tag addTarget:self action:@selector(tagTapped:) forControlEvents:UIControlEventTouchUpInside];

However I don't see such a method implemented anywhere and when I tried to implement it myself in SMTagField it don't seem to get fired. Am I missing something obvious?

**Comment by freak4pc** [comment] 2013-11-10 15:52
Hey, That's just a mistake from an old project. I'll remove that later.
Generally speaking, since this is an input field, clicking the tags isn't supposed to do anything.

**Comment by Jack-s** [comment] 2013-11-10 16:22
OK, but aren't the tags themselves UIButtons? Anyway is there a way to get it to trigger something? I was thinking of using a combination of a second SMTagField in the input accessary view plus a delegate method to add a sort of autocomplete/autosuggest functionality. I basically have that part working, but I want that when the user taps on one of the suggested tags it should add add that tag to the tags they are entering.

**Comment by freak4pc** [comment] 2013-11-10 16:26
SMTags are buttons because I used them as buttons in an older version...
Usually you wouldnt want content in a text field trigger-able ... Which is why I didn't implement it. 

Also to be honest, there was no demand for this feature by anyone as of now. 
If you want to open it as a separate issue ill mark it as an enhancement and try to add it in the next version. 

You could, for now, implement that method yourself inside SMTagField. Not a very "pretty" solution but if its urgent you could go that path.

**Comment by Jack-s** [comment] 2013-11-10 16:30
OK thanks, I was thinking of just forking and trying to add the feature myself. However when I tried implementing the `tagtapped:` method in SMTagField it didn't get triggered.

**Comment by freak4pc** [comment] 2013-11-10 16:33
I think I just had a UIScrollView or a [EasyTableView](https://github.com/alekseyn/EasyTableView) (horizontal) with SMTags instead of text input, and then i implemented that button. Feel free to fork and if its good enough i'd love to see your patch.

**Comment by Jack-s** [comment] 2013-11-10 17:59
OK will do. 

 I think the problem I'm having has to do with the paddingView or tagsView intercepting the touch events. I've tried subclassing them and passing on the events but have been unsuccessful thus far (so maybe I'm on the wrong track).
